# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ojDWOcU4dQHOYdqpmt8mMet_cZJzGFA
"""

import streamlit as st
import pickle
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# Load Model and Vectorizer
model = pickle.load(open("sentiment_model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

# Function to clean text
def clean_text(text):
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^A-Za-z\s]", "", text)
    text = text.lower()
    text = " ".join([w for w in text.split() if w not in stopwords.words('english')])
    return text

# Streamlit App
st.set_page_config(page_title="Text Classification App", page_icon="🧠")
st.title("🧠 NLP Text Classification App")
st.write("Predict Sentiment, Emotion, or Sarcasm from input text")

mode = st.selectbox("Select Mode", ["Sentiment Detection", "Emotion Detection", "Sarcasm Detection"])
user_input = st.text_area("✍️ Enter your text here:")

if st.button("Classify"):
    if user_input.strip() == "":
        st.warning("Please enter some text!")
    else:
        clean = clean_text(user_input)
        vec = vectorizer.transform([clean]).toarray()
        pred = model.predict(vec)[0]
        label = "😊 Positive" if pred == 1 else "😠 Negative"
        st.success(f"Predicted Label: {label}")

st.markdown("---")
st.caption("Developed by Himani Sharma| NLP Lab Mini Project (BCS-DS-658)")
