# -*- coding: utf-8 -*-
"""NLP_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpiDKGIs4p5JJlnL2DidCF-shr8MAbyI
"""

import streamlit as st
import pickle
import re
import nltk
from nltk.corpus import stopwords

# Download stopwords if needed
nltk.download('stopwords')

# ---------------------------
# Load Saved Model & Vectorizer
# ---------------------------
model = pickle.load(open("sentiment_model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

# ---------------------------
# Text Cleaning Function
# ---------------------------
def clean_text(text):
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^A-Za-z\s]", "", text)
    text = text.lower()
    text = " ".join(
        [w for w in text.split() if w not in stopwords.words('english')]
    )
    return text

# ---------------------------
# Streamlit UI
# ---------------------------
st.set_page_config(page_title="Sentiment Classifier", page_icon="💬")

st.title("💬 Sentiment Classification App")
st.write("Enter any text below and the model will predict its sentiment.")

# User Input
user_text = st.text_area("Enter your text here:", height=150)

if st.button("Predict Sentiment"):
    if user_text.strip() == "":
        st.warning("Please enter some text to analyze.")
    else:
        # Clean and vectorize input
        clean = clean_text(user_text)
        vec = vectorizer.transform([clean]).toarray()

        # Predict
        prediction = model.predict(vec)[0]

        # Display Result
        if prediction == "positive":
            st.success(f"Sentiment: **Positive 😊**")
        elif prediction == "negative":
            st.error(f"Sentiment: **Negative 😠**")
        else:
            st.info(f"Sentiment: **Neutral 😐**")

# Footer
st.write("---")
st.caption("Built by Revanth • NLP Mini Project")